{% set version = "0.2.12" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggdag
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggdag_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggdag/ggdag_{{ version }}.tar.gz
  sha256: 9d5621290eb234e9c5c2e8cb357e1e5267a00a9549b6c45ae7e760989de2b160

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-dagitty
    - r-dplyr
    - r-forcats
    - r-ggplot2 >=3.0.0
    - r-ggraph >=2.0.0
    - r-ggrepel
    - r-igraph
    - r-magrittr
    - r-pillar
    - r-purrr
    - r-rlang
    - r-stringr
    - r-tibble
    - r-tidygraph
  run:
    - r-base
    - r-dagitty
    - r-dplyr
    - r-forcats
    - r-ggplot2 >=3.0.0
    - r-ggraph >=2.0.0
    - r-ggrepel
    - r-igraph
    - r-magrittr
    - r-pillar
    - r-purrr
    - r-rlang
    - r-stringr
    - r-tibble
    - r-tidygraph

test:
  commands:
    - $R -e "library('ggdag')"           # [not win]
    - "\"%R%\" -e \"library('ggdag')\""  # [win]

about:
  home: https://github.com/r-causal/ggdag, https://r-causal.github.io/ggdag//
  license: MIT
  summary: Tidy, analyze, and plot directed acyclic graphs (DAGs). 'ggdag' is built on top of 'dagitty', an R package that uses the 'DAGitty' web tool (<http://dagitty.net>) for creating and analyzing DAGs. 'ggdag' makes it easy to tidy and plot 'dagitty' objects using 'ggplot2' and 'ggraph', as well as common analytic and
    graphical functions, such as determining adjustment sets and node relationships.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
